FROM laundree/%%RESIN_MACHINE_NAME%%-till-base:latest

WORKDIR /usr/src

# Move package.json to filesystem
COPY "$SOURCEFOLDER/package.json" ./

# NPM i app
RUN JOBS=MAX npm i --production

# Move app to filesystem
COPY "$SOURCEFOLDER" ./

# NPM rebuild node native modules after electron is installed.
RUN ./node_modules/.bin/electron-rebuild

## uncomment if you want systemd
ENV INITSYSTEM on

# Start app
CMD ["bash", "/usr/src/start.sh"]
